query MyQuery {
  sonyCategory: productCategories(where: {slug: "sony"}) {
    nodes {
      slug
      name
      id
      children {
        nodes {
          id
          databaseId
          name
          slug
          children {
            edges {
              node {
                id
                databaseId
                name
                slug
              }
            }
          }
        }
      }
    }
  }
  xboxCategory: productCategories(where: {slug: "xbox"}) {
    nodes {
      slug
      name
      id
      children {
        nodes {
          id
          databaseId
          name
          slug
          children {
            edges {
              node {
                id
                databaseId
                name
                slug
              }
            }
          }
        }
      }
    }
  }
  nintendoCategory: productCategories(where: {slug: "nintendo"}) {
    nodes {
      slug
      name
      id
      children {
        nodes {
          id
          databaseId
          name
          slug
          children {
            edges {
              node {
                id
                databaseId
                name
                slug
              }
            }
          }
        }
      }
    }
  }
}