query 
{
  viewer { databaseId } 
  products(first: 24) {
    nodes {
      databaseId
      name
      onSale
      slug
      status
      image {
        sourceUrl
      }
      ... on SimpleProduct {
        databaseId
        price
        stockStatus
        regularPrice
        salePrice
      }
      ... on VariableProduct {
        databaseId
        price
        regularPrice
        salePrice
        variations {
          nodes {
            price
            regularPrice
            salePrice
          }
        }
      }
    }
  }
}
