query FETCH_ORDERS_QUERY($first: Int = 10, $order: OrderEnum = ASC) {
  orders(first: $first, where: {orderby: {field: DATE, order: $order}}) {
    nodes {
      currency
      customerNote
      date
      dateCompleted
      datePaid
      discountTotal(format: RAW)
      databaseId
      needsPayment
      needsProcessing
      paymentMethod
      paymentMethodTitle
      total(format: RAW)
      transactionId
      lineItems {
        nodes {
          quantity
          productId
          orderId
          product {
            node {
              databaseId
              slug
              name
              title(format: RENDERED)
              image {
                sourceUrl
                link
              }
            }
          }
          subtotal
          total
        }
      }
      shippingTotal(format: RAW)
      billing {
        address1
        address2
        city
        country
        firstName
        lastName
        postcode
      }
      shipping {
        address1
        address2
        city
        country
        firstName
        lastName
        postcode
      }
    }
  }
}