# $statuses: [OrderStatusEnum] = CANCELLED,
#statuses: $statuses,
query FETCH_ORDERS_QUERY($after: String = "", $before: String = "", $first: Int = 10, $last: Int = 10, $search: String = "", $order: OrderEnum = ASC) {
  orders(
    first: $first
    before: $before
    after: $after
    last: $last
    where: {  search: $search, orderby: {field: DATE, order: $order} }
  ) {
    nodes {
      currency
      customerNote
      date
      dateCompleted
      datePaid
      discountTotal(format: RAW)
      id
      needsPayment
      needsProcessing
      paymentMethod
      paymentMethodTitle
      status
      total(format: RAW)
      transactionId
      lineItems {
        nodes {
          quantity
          productId
          orderId
          product {
            node {
              name
              title(format: RENDERED)
              image {
                sourceUrl
                link
              }
            }
          }
          subtotal
          total
        }
      }
      shippingTotal(format: RAW)
    }
  }
}