query MyQuery($search: String = "", $categoryIn: [String] = "", $exclude: [Int] = 10 $first: Int = 10, $last: Int = 10, $before: String = "", $after: String = "") {
  products(
    where: {search: $search, categoryIn: $categoryIn exclude: $exclude }
    first: $first
    last: $last
    after: $after
    before: $before
  ){
    nodes {
      databaseId
      name
      onSale
      slug
      sku
      status
      image {
        sourceUrl
      }
      ... on SimpleProduct {
        databaseId
        price
        stockStatus
        regularPrice
        salePrice
      }
      ... on VariableProduct {
        databaseId
        price
        regularPrice
        salePrice
        variations {
          nodes {
            price
            regularPrice
            salePrice
          }
        }
      }
    }
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
  }
}